[build]
builder = "nixpacks"
nixpacksConfig = { node_version = "18" }
buildCommand = "cd server && npm install"

[deploy]
startCommand = "cd server && npm start"
restartPolicyType = "ON_FAILURE"
healthcheckPath = "/"

[nixpacks]
# Pastikan node.js dan npm terinstall
setup = ["nodejs_18", "npm-9_x"]

[service]
internal_port = 8080